version: '3'

services:
  login_register:
    build: ./login_register
    container_name: login-register-form
    ports:
      - "8000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: user-account-db
    environment:
      POSTGRES_DB: UserAccounts
      POSTGRES_USER: testdev
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"